### ISSUE TITLE
Fix BGM switching for Answer Arcs and Rei

### ISSUE THREAD

**Issue by drojf** [07th-mod/meakashi#80]
Before we implemented BGM switching, some BGM were copied directly into the BGM folder. While we removed most of these, the Answer Arcs and Rei still copy certain BGM to the BGM folder. These BGM won't work correctly with our BGM switching function - the pre-april update BGM will play no matter your choice of BGM.

These BGM are mostly just BGM copied from the Question Arcs so they can be used in the Answer arcs. The reason this was done was so that we could better match the Console game, which uses these QA BGM.

As an aside, we also include one? BGM which does not overwrite anything (from the console game). This can be treated the same way as the rest of the files, see below.

----

To fix this issue and avoid future confusion, these BGM should be included in our BGM archive. Currently, these extra BGM reside in:
 - ch5: There are BGM included in the graphics archive
 - ch6, ch7, ch8: There are BGM included in the 'script' archive / committed to the repository.
 - ch9: There is one 'bgm' which is actually a sound effect included in the 'script' archive / committed to the repository.

For the BGM which are copied from the Question Arcs, we need to copy both the Post-April Update version, but also the Original Version. Other Console Specific BGM only have one version.

It would technically work if we copied these to the BGM/OGBGM folders, but it might be better to put them in separate folders (ExtraBGM and ExtraOGBGM?). Generally I've always thought of the BGM folder to never be touched, as that should only contain files that come with the game. But I haven't decided the best way to do this yet.

Once those files are in place, we just update the game script (if necessary) to search for the extra BGM in the other folder (if necessary).

### TODO

- [x] Collect extra BGM for the answer arcs into one package 
- [x] Decide on folder structure (if any) to put these extra BGM 
- [x] Update Answer Arcs BGM archive with these extra BGM files
- [x] Update game script (if necessary) to use new BGM folders
- [x] Remove extra BGM from git repo and graphics archives (**ONLY** once updated ch5-7 are released)
- [x] Regenerate BGM name database with new BGM
- ~~Update in-game description of New BGM/SE to say we may change some BGM to better match Console?~~ I don't think this is necessary

### Rei TODO

~~This is optional, it would only tidy up the Rei BGM. Considering it's just one file, probably not worth the trouble.~~

- [x] Move that one BGM in the repo to the existin BGM archive
- [x] Update archive with bgmInfo

**Comment by drojf** [comment]
Here are the extra BGM and SE used for each chapter (ep8 uses no extra BGM)

```
├───HigurashiEp05_Data
│   └───StreamingAssets
│       ├───BGM
│       │       hm05_20.ogg
│       │       msys01.ogg
│       │       msys03.ogg
│       │       msys06.ogg
│       │       msys07.ogg
│       │       msys08.ogg
│       │       msys09.ogg
│       │       msys15.ogg
│       │       msys17.ogg
│       │       msys23.ogg
│       │       msys27.ogg
│       │       msys30.ogg
│       │       song_you.ogg
│       │
│       └───SE
│               wa_001.ogg
│               wa_003.ogg
│               wa_005.ogg
│               wa_006.ogg
│               wa_007.ogg
│               wa_011.ogg
│               wa_012.ogg
│               wa_013.ogg
│               wa_016.ogg
│               wa_018.ogg
│               wa_019.ogg
│               wa_020.ogg
│               wa_022.ogg
│               wa_023.ogg
│               wa_025.ogg
│               wa_027.ogg
│               wa_032.ogg
│
├───HigurashiEp06_Data
│   └───StreamingAssets
│       ├───BGM
│       │       msys06.ogg
│       │       msys07.ogg
│       │       msys08.ogg
│       │       msys17.ogg
│       │       msys23.ogg
│       │       msys30.ogg
│       │       song_ps2ed1.ogg
│       │
│       └───SE
│               thunder.ogg
│               wa_001.ogg
│               wa_003.ogg
│               wa_007.ogg
│               wa_011.ogg
│               wa_013.ogg
│               wa_023.ogg
│               wa_025.ogg
│               wa_041.ogg
│               wa_045.ogg
│
└───HigurashiEp07_Data
    └───StreamingAssets
        ├───BGM
        │       msys06.ogg
        │       msys15.ogg
        │       msys17.ogg
        │       msys23.ogg
        │
        └───SE
                wa_001.ogg
                wa_003.ogg
                wa_007.ogg
                wa_011.ogg
                wa_016.ogg
                wa_033.ogg
                wa_036.ogg
                wa_041.ogg

└───HigurashiEp08_Data  // No extra BGM or SE used in this chapter
```

And when merged together:

```
├───BGM
│       hm05_20.ogg
│       msys01.ogg
│       msys03.ogg
│       msys06.ogg
│       msys07.ogg
│       msys08.ogg
│       msys09.ogg
│       msys15.ogg
│       msys17.ogg
│       msys23.ogg
│       msys27.ogg
│       msys30.ogg
│       song_ps2ed1.ogg
│       song_you.ogg
│
└───SE
        thunder.ogg
        wa_001.ogg
        wa_003.ogg
        wa_005.ogg
        wa_006.ogg
        wa_007.ogg
        wa_011.ogg
        wa_012.ogg
        wa_013.ogg
        wa_016.ogg
        wa_018.ogg
        wa_019.ogg
        wa_020.ogg
        wa_022.ogg
        wa_023.ogg
        wa_025.ogg
        wa_027.ogg
        wa_032.ogg
        wa_033.ogg
        wa_036.ogg
        wa_041.ogg
        wa_045.ogg
```

Here is an archive with the merged BGM files for chapters 5-7: https://1drv.ms/u/s!Ar-lAVeetlqhhL1cwSQQaZpUNEQGjA?e=FUlSsJ

**Comment by drojf** [comment]
Here is an 'Extra BGM Pack' containing the bgm + folder structure to be merged with the existing Kai BGM pack we use.

I realized yesterday that the question arcs OGBGM/OGSE are likely never used when you have the OGBGM/GIN BGM setting on, because GIN's scripts wouldn't reference them. But since it only adds 21Mb overhead, I've add them anyway.

extra bgm pack: https://1drv.ms/u/s!Ar-lAVeetlqhhL1objObUOZJT9jE2Q?e=wHcVfU

**Comment by drojf** [comment]
I've created an updated version of the Answer BGM pack. 

https://1drv.ms/u/s!Ar-lAVeetlqhhL4mTrUjjeWnAYs5PA?e=QurWHO

The following changelog is included inside.

# Version 1.1 - 2022-11-04

- See PR https://github.com/07th-mod/meakashi/issues/80
- Add 'ExtraBGM' and 'ExtraSE' which mostly consists of BGM from the question arcs, but also a few BGM from the console game. These contain the post-april update BGM and SE of the question arcs tracks.
- Add corresponding SE to the 'OGSE' folder to mirror the SE in 'ExtraSE' - these are taken from GIN's BGM
- Update OGBGM folder (GIN BGM) msys17, msys23, msys27 to be consistent with question arcs
    - NOTE: I don't think the question arcs BGM (msysXX) are used if you have the OGBGM enabled, due to GIN's version of the script never using them. But I'm making them consistent anyway.
    - Previously, the OGBGM Question arcs used the remastered versions of these three songs, and the Answer arcs OGBGM used the original midi Japanese release's version. Now both OGBGM will use the remastered version. 
        - There is an issue related to this: https://github.com/07th-mod/meakashi/issues/49
        
---

Here are the different versions of those three modified BGM if you want to compare them
[bgm comparison](https://github.com/07th-mod/meakashi/files/9937195/answer_old_2021-03-20.zip)

**Comment by drojf** [comment]
This issue should be fixed now.

**Comment by drojf** [comment]
I just noticed there are the following BGM and SE in the Ch8 Voices archive (previously I thought there were no extra BGM/SE used in ch8):

- `SE/wa_003.ogg`
- `BGM/msys06.ogg`
- `BGM/msys32.ogg`

Unfortunately, msys32 is not included in the BGM archive I updated, so I'll need to update it to add that one.

# TODO

- [ ] Update kai BGM archive with msys32.ogg in both ExtraBGM and OGBGM folders
- [ ] Add that one song to the bgmInfo.json
- [ ] Upload new bgm archive to server
- [ ] Update the ch8 script file to use the ExtraBGM folder
- [ ] Release a new ch8
- [ ] Remove BGM and SE from ch8 voices archive (along with other changes)
